name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.15
  permission_handler: ^12.0.0+1
  google_fonts: ^6.1.0
  location: ^8.0.0
  app_settings: ^6.1.1
  path_provider: ^2.1.2
  csv: ^6.0.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  supabase_flutter: ^2.9.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/1024.png
    - assets/icon/google_g.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/app_icon.png"
  image_path_android: "assets/icon/1024.png"
  adaptive_icon_foreground: "assets/icon/1024.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/1024.png
  android_12:
    image: assets/icon/1024.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icon/1024.png
    icon_background_color_dark: "#121212"
  web: false
  android: true
  ios: true
  fullscreen: true
